### ISSUE TITLE
Core distribution board design/Layout

### ISSUE THREAD

**Issue by ThorsHamster** [Squiddrone/Squiddrone#118]

**Comment by c0nwild** [comment]
![SquidDrone_CoreDistributionBoard_Bottom](https://user-images.githubusercontent.com/42233292/77473540-e98e3100-6e15-11ea-89c6-f87e0f01eb45.png)
![SquidDrone_CoreDistributionBoard_Schematics](https://user-images.githubusercontent.com/42233292/77473543-ea26c780-6e15-11ea-96bc-b70aec999cd2.png)
![SquidDrone_CoreDistributionBoard_Top](https://user-images.githubusercontent.com/42233292/77473546-eabf5e00-6e15-11ea-968c-814de0bbeee9.png)

**Comment by elheck** [comment]
Open until design rule checker of producer accepted pcb  layout
